project:
  type: website
  resources:
    - googleae5461e8dc14cfbf.html  # 이 줄을 추가하세요!

website:
  title: "Bora Kang"
  description: "Academic website of Bora Kang"
  navbar:
    background: light
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Publications
        href: publications.qmd
      - text: Teaching
        href: teaching.qmd
      - text: Conferences
        href: conferences.qmd
      - text: CV
        href: cv.qmd

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true