## Conference Presentations

### Papers Presented

- “**'Slightly Out of Tune': Affective Drift and Weird Modernism in Virginia Woolf’s *Mrs. Dalloway***”  
  Modernist Studies Association / British Association for Modernist Studies (MSA/BAMS) | Loughborough, UK (July 2026)
- “**Affective Drift after Brexit: Emotion and National Belonging in Ali Smith’s *Autumn* and *Winter***”  
  Northeast Modern Language Association (NeMLA) | Pittsburgh, PA (March 2026)
- “**Streaming Heritage and the Circulation of Feeling**”  
  American Comparative Literature Association (ACLA) | Montréal, Canada (February 2026)
- “**Representing Otherness in Comfort Women Narratives**”  
  London Centre for Interdisciplinary Research Conference | London, UK (December 2024)
- “**Asian Diaspora in British Literature**”  
  American Comparative Literature Association (ACLA) | Chicago, IL (March 2023)
- “**Professional Resources for International PhD TA and Candidate in the English Program**”  
  Modern Language Association (MLA) | San Francisco, CA (January 2023)
- “***The Remains of the Day*: Scaffolding for Shrinking Englishness**”  
  Northeast Modern Language Association (NeMLA) | Virtual (March 2021)
- “**Kodak Eye and Aesthetics of the Novel**”  
  Northeast Modern Language Association (NeMLA) | Boston, MA (March 2020)
- “**Rethinking Mimesis: Novel to Novel to Film**” (Roundtable)  
  Northeast Modern Language Association (NeMLA) | Boston, MA (March 2020)
- “**I See, Therefore I Am?: Focusing on D. H. Lawrence’s Essays and Three Episodes from *Black Mirror***”  
  College English Association (CEA) | New Orleans, LA (March 2019)
- “**Limitations of Transnational Identity: *A Gesture Life***”  
  Northeast Modern Language Association (NeMLA) | Washington, DC (March 2019)
- “**Constructions of 'Comfort Women' Experiences: An Analysis of Recent Films**”  
  Weaponizing People: Militarization and Armed Conflict in Asia | Binghamton, NY (November 2018)

---

### Panels Organized & Chaired

- **Affect at the Limit: Postcolonial Feeling and Form**  
  Northeast Modern Language Association (NeMLA) | Newport, RI (Forthcoming March 2027)
- **Feeling the Nation: Emotion, Identity, and Memory in Literature and Media** (Part 1 & 2)  
  Northeast Modern Language Association (NeMLA) | Pittsburgh, PA (March 2026)
- **Unresolved Feeling, Fragments of Belonging: Emotion Across Text and Screen**  
  American Comparative Literature Association (ACLA) | Montréal, Canada (February 2026)
- **British Literature and Film: Finding “Englishness”**  
  Northeast Modern Language Association (NeMLA) | Virtual (March 2021)
- **Literature, New Media and Perception** (Part 1 & 2)  
  Northeast Modern Language Association (NeMLA) | Boston, MA (March 2020)
- **The Circle of the Adaptations: Beyond the Boundaries of Genres** (Roundtable)  
  Northeast Modern Language Association (NeMLA) | Boston, MA (March 2020)